# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  inherit (lib) types mkEnableOption mkOption;
in
{
  moreQuickReactions = {
    enable = mkEnableOption "Increases the number of reactions available in the Quick React hover menu (Vencord-only)";
    reactionCount = mkOption {
      default = 5;
      description = "Number of reactions (0-42)";
      type = types.int;
    };
  };
  oneko = {
    enable = mkEnableOption "cat follow mouse (real) (Vencord-only)";
  };
  showMeYourName = {
    enable = mkEnableOption "Display usernames next to nicks, or no nicks at all";
    mode = mkOption {
      default = "user-nick";
      description = "How to display usernames and nicks";
      type = types.enum [
        "user-nick"
        "nick-user"
        "user"
      ];
    };
    friendNicknames = mkOption {
      default = "dms";
      description = "How to prioritise friend nicknames over server nicknames";
      type = types.enum [
        "dms"
        "always"
        "fallback"
      ];
    };
    displayNames = mkOption {
      default = false;
      description = "Use display names in place of usernames";
      type = types.bool;
    };
    inReplies = mkOption {
      default = false;
      description = "Also apply functionnality to reply previews";
      type = types.bool;
    };
  };
  spotifyControls = {
    enable = mkEnableOption "Adds a Spotify player above the account panel (Vencord-only)";
  };
  vencordToolbox = {
    enable = mkEnableOption "Adds a button to the titlebar that houses Vencord quick actions (Vencord-only)";
    showPluginMenu = mkOption {
      default = true;
      description = "Show the plugins menu in the toolbox";
      type = types.bool;
    };
  };
}
